[package]
name = "json-pragmatic"
version = "0.1.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
edition = "2018"

[dependencies]
vrp-pragmatic = { path = "../../vrp-pragmatic" }
vrp-core = { path = "../../vrp-core" }
vrp-solver = { path = "../../vrp-solver" }
