[package]
name = "vrp-cli"
version = "1.0.1"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "../README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "A command line interface for VRP solver"

[lib]
name = "vrp_cli"
crate-type = ["cdylib", "lib"]

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.0.1" }
vrp-scientific = { path = "../vrp-scientific", version = "1.0.1" }
vrp-pragmatic = { path = "../vrp-pragmatic", version = "1.0.1" }
vrp-solver = { path = "../vrp-solver", version = "1.0.1" }

clap = "2.33.0"
csv = "1.1.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.60", features = ["serde-serialize"] }