[package]
name = "vrp-cli"
version = "0.1.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
edition = "2018"

[dependencies]
vrp-core = { path = "../vrp-core" }
vrp-scientific = { path = "../vrp-scientific" }
vrp-pragmatic = { path = "../vrp-pragmatic" }
vrp-solver = { path = "../vrp-solver" }

clap = "2.33.0"
csv = "1.1.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
