[package]
name = "vrp-pragmatic"
version = "1.0.3"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.0.3" }
vrp-solver = { path = "../vrp-solver", version = "1.0.3" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

chrono = "0.4"
rand = "0.7.2"

[dev-dependencies]
proptest = "0.9.5"
uuid = { version = "0.8", features = ["v4"] }
