[package]
name = "solver"
version = "0.1.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
scientific = { path = "../scientific" }
clap = "2.33.0"
